export const ActionTypes = {
  GET_POST: 'blog/GET_POST',
  GET_POST_SUCCESS: 'blog/GET_POST_SUCCESS',
  GET_POST_FAILED: 'blog/GET_POST_FAILED',

  GET_POST_BY_SLUG: 'blog/GET_POST_BY_SLUG',
  GET_POST_BY_SLUG_SUCCESS: 'blog/GET_POST_BY_SLUG_SUCCESS',
  GET_POST_BY_SLUG_FAILED: 'blog/GET_POST_BY_SLUG_FAILED',

  POST_TAG: "blog/POST_TAG",
  POST_TAG_SUCCESS: "blog/POST_TAG_SUCCESS",
  POST_TAG_FAILED: "blog/POST_TAG_FAILED",

  DELETE_POST: "blog/DELETE_POST",
  DELETE_POST_SUCCESS: "blog/DELETE_POST_SUCCESS",
  DELETE_POST_FAILED: "blog/DELETE_POST_FAILED",

  UPDATE_POST: "blog/UPDATE_POST",
  UPDATE_POST_SUCCESS: "blog/UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILED: "blog/UPDATE_POST_FAILED",

  UPLOAD_FILE: "blog/UPLOAD_FILE",
  UPLOAD_FILE_SUCCESS: "blog/UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILED: "blog/UPLOAD_FILE_FAILED",
  
  GET_POST_BY_TAG: 'blog/GET_POST_BY_TAG',
  GET_POST_BY_TAG_SUCCESS: 'blog/GET_POST_BY_TAG_SUCCESS',
  GET_POST_BY_TAG_FAILED: 'blog/GET_POST_BY_TAG_FAILED',
};

export default ActionTypes;
